### ISSUE TITLE
Wrong value when decrypting

### ISSUE THREAD

**Issue by MasterSpl1nter** [odzhan/aes#8]
Hi, I'm trying to decrypt previously encrypted bytes, but for some reason I get the wrong decrypted value, I hope you can tell me where is my mistake.
(IN value should be equal to DEC value.)
Thanks.

[aes_text.txt](https://github.com/odzhan/aes/files/233480/aes_text.txt)

**Comment by odzhan** [comment]
You need to use same IV for decryption. Before calling aes_cbc_dec, do hex2bin (iv.v8, cbc_iv[0]); again.

**Comment by MasterSpl1nter** [comment]
Thanks!
